"use strict";
exports.__esModule = true;
var validators_1 = require("./validators/validators");
var constant_1 = require("./constant/constant");
var email = 'abc@gmail.com';
var zipCode = '380058';
var number = '9687074450';
console.log("Valid Email Id OR Not: " + new validators_1.ValidatorCLS().isValidStr(email, constant_1.Constants.emailRegex));
console.log("Valid zipcode Id OR Not: " + new validators_1.ValidatorCLS().isValidStr(zipCode, constant_1.Constants.zipcode));
console.log("Valid number Id OR Not: " + new validators_1.ValidatorCLS().isValidStr(number, constant_1.Constants.number));
