var fname = "Shivam";
var lname = "Shukla";
var fullnam = fname + " " + lname;
var integ = 45;
var float = 45.25;
var summ = integ + float;
console.log("Fname:" + fname);
console.log("Lname:" + lname);
console.log("Full Name:" + fullnam);
console.log("Integer:" + integ);
console.log("Float:" + float);
console.log("Sum:" + summ);
